name: Merged
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install neovim
      run: |
            mkdir ~/programs
            wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -P ~/programs
            chmod u+x ~/programs/nvim.appimage
            echo 'export PATH="$PATH:~/programs"'>> ~/.profile
            mv ~/programs/nvim.appimage ~/programs/nvim 
            mkdir -p ~/.config/nvim
    - name: Use kickstart
      env:
        APPIMAGE_EXTRACT_AND_RUN: 1
        NO_CLEANUP: 1
      run: |
             git clone https://github.com/nvim-lua/kickstart.nvim.git ~/.config/nvim
             ~/programs/nvim --headless -c 'TsInstall go' -c 'qa'
             sleep 30
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: run tests
      env:
        APPIMAGE_EXTRACT_AND_RUN: 1
        NO_CLEANUP: 1
      run: |
        make tests-ci

          
